<?php

namespace App\Http\Controllers;

use Illuminate\View\View;

class ToolsIndexController extends Controller
{
	public function show(string $locale): View
	{
		$sections = [
			[
				'key' => 'finance',
				'title_nl' => 'Financieel & compliance',
				'title_en' => 'Finance & compliance',
				'subtitle_nl' => 'Checks op klant- en betaalgegevens.',
				'subtitle_en' => 'Checks on customer and payment data.',
				'tools' => [
					[
						'slug' => 'bookkeeping',
						'route' => 'tools.bookkeeping.index',
						'title_nl' => 'Boekhouden', 'title_en' => 'Bookkeeping',
						'desc_nl' => 'Eenvoudige administratie: transacties met BTW, categorieën en filterbare overzichten.',
						'desc_en' => 'Simple bookkeeping: VAT-aware transactions, categories and filterable overviews.',
						'badge_nl' => 'Pro', 'badge_en' => 'Pro',
						'icon' => 'book',
					],
					[
						'slug' => 'iban-check',
						'route' => 'tools.iban-check',
						'title_nl' => 'IBAN-check', 'title_en' => 'IBAN check',
						'desc_nl' => 'Technische validatie + heuristische risico-analyse op basis van naam en structuur.',
						'desc_en' => 'Technical validation plus heuristic risk analysis on name and structure.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'credit-card',
					],
					[
						'slug' => 'vat-check',
						'route' => 'tools.vat-check',
						'title_nl' => 'BTW-check (VIES)', 'title_en' => 'VAT check (VIES)',
						'desc_nl' => 'Valideer EU-BTW-nummers rechtstreeks via VIES. Inclusief naam en adres van de houder.',
						'desc_en' => 'Validate EU VAT numbers directly via VIES. Includes holder name and address.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'check-badge',
					],
					[
						'slug' => 'postcode-check',
						'route' => 'tools.postcode-check',
						'title_nl' => 'Postcode sanity check', 'title_en' => 'Postcode sanity check',
						'desc_nl' => 'Checkt NL/BE/DE-postcodes op formaat + opvallende invoer — handig voor exports en fulfilment.',
						'desc_en' => 'Checks NL/BE/DE postcodes on format + unusual input — useful for exports and fulfilment.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'map-pin',
					],
					[
						'slug' => 'shipping-rates',
						'route' => 'tools.shipping-rates',
						'title_nl' => 'Verzendtarieven', 'title_en' => 'Shipping rates',
						'desc_nl' => 'Vergelijk PostNL en DHL tarieven per zone en gewicht. Bereken de goedkoopste match incl. handling.',
						'desc_en' => 'Compare PostNL and DHL rates by zone and weight. Calculate the cheapest match incl. handling.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'truck',
					],
				],
			],
			[
				'key' => 'text',
				'title_nl' => 'Tekst & data',
				'title_en' => 'Text & data',
				'subtitle_nl' => 'Ontwikkelaars- en administratie-hulpjes.',
				'subtitle_en' => 'Developer and admin helpers.',
				'tools' => [
					[
						'slug' => 'json-formatter',
						'route' => 'tools.json-formatter',
						'title_nl' => 'JSON formatter', 'title_en' => 'JSON formatter',
						'desc_nl' => 'Valideer, formatteer of minify JSON. Fouten worden met regel- en kolomnummer aangegeven.',
						'desc_en' => 'Validate, format or minify JSON. Errors pinpointed by line and column.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'braces',
					],
					[
						'slug' => 'diff',
						'route' => 'tools.diff',
						'title_nl' => 'Diff checker', 'title_en' => 'Diff checker',
						'desc_nl' => 'Vergelijk twee teksten regel-voor-regel. Toevoegingen, verwijderingen en ongewijzigde regels gemarkeerd.',
						'desc_en' => 'Compare two texts line by line. Additions, removals and unchanged lines marked.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'compare',
					],
				],
			],
			[
				'key' => 'network',
				'title_nl' => 'Netwerk & analyse',
				'title_en' => 'Network & analysis',
				'subtitle_nl' => 'Wat zien externe diensten van jouw verbinding?',
				'subtitle_en' => 'What do external services see about your connection?',
				'tools' => [
					[
						'slug' => 'ip-lookup',
						'route' => 'tools.ip-lookup',
						'title_nl' => 'Wat is mijn IP', 'title_en' => 'What is my IP',
						'desc_nl' => 'Toont jouw publieke IP + land, stad, provider en netwerk-type (mobiel / datacenter / wifi).',
						'desc_en' => 'Shows your public IP + country, city, provider and network type (mobile / datacenter / wifi).',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'globe',
					],
					[
						'slug' => 'speedtest',
						'route' => 'tools.speedtest',
						'title_nl' => 'Internet snelheidstest', 'title_en' => 'Internet speed test',
						'desc_nl' => 'Meet ping, download en upload vanuit je browser. Geen app, geen account nodig.',
						'desc_en' => 'Measures ping, download and upload from your browser. No app, no account.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'gauge',
					],
				],
			],
			[
				'key' => 'identity',
				'title_nl' => 'Toegang & identity',
				'title_en' => 'Access & identity',
				'subtitle_nl' => 'Wie heeft toegang tot welk systeem, en klopt dat nog?',
				'subtitle_en' => 'Who has access to which system, and is that still correct?',
				'tools' => [
					[
						'slug' => 'accessguard',
						'route' => 'accessguard.landing',
						'title_nl' => 'AccessGuard', 'title_en' => 'AccessGuard',
						'desc_nl' => 'Access matrix: wie heeft toegang tot welk systeem. Periodieke reviews, onboarding en offboarding in één overzicht.',
						'desc_en' => 'Access matrix: who has access to which system. Periodic reviews, onboarding and offboarding in one view.',
						'badge_nl' => 'Pro', 'badge_en' => 'Pro',
						'icon' => 'key',
					],
					[
						'slug' => 'security-radar',
						'route' => 'tools.radar.index',
						'title_nl' => 'Security Radar', 'title_en' => 'Security Radar',
						'desc_nl' => 'Scan websites op security-headers, TLS-certificaten, cookies en CMP-compliance. Dagelijkse cron + diff-detect.',
						'desc_en' => 'Scan websites for security headers, TLS certificates, cookies and CMP compliance. Daily cron + diff detection.',
						'badge_nl' => 'Pro', 'badge_en' => 'Pro',
						'icon' => 'shield-check',
					],
				],
			],
			[
				'key' => 'hobby',
				'title_nl' => 'Hobby',
				'title_en' => 'Hobby',
				'subtitle_nl' => 'Speciale lookups voor verzamelaars.',
				'subtitle_en' => 'Specialist lookups for collectors.',
				'tools' => [
					[
						'slug' => 'lego-lookup',
						'route' => 'tools.lego-lookup',
						'title_nl' => 'LEGO Element Finder', 'title_en' => 'LEGO Element Finder',
						'desc_nl' => 'Zoek een LEGO-onderdeel op Element ID. Toont part, kleur, afbeelding en links naar Rebrickable en BrickLink.',
						'desc_en' => 'Look up a LEGO part by Element ID. Shows the part, colour, image and links to Rebrickable and BrickLink.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'blocks',
					],
				],
			],
			[
				'key' => 'files',
				'title_nl' => 'Bestanden & media',
				'title_en' => 'Files & media',
				'subtitle_nl' => 'Bewerk documenten en afbeeldingen snel.',
				'subtitle_en' => 'Quick document and image edits.',
				'tools' => [
					[
						'slug' => 'pdf-merge',
						'route' => 'tools.pdf-merge',
						'title_nl' => 'PDF merge', 'title_en' => 'PDF merge',
						'desc_nl' => 'Voeg meerdere PDF\'s samen tot één bestand. Sleep om volgorde aan te passen.',
						'desc_en' => 'Combine multiple PDFs into one file. Drag to reorder.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'files',
					],
					[
						'slug' => 'pdf-redact',
						'route' => 'tools.pdf-redact',
						'title_nl' => 'PDF redact', 'title_en' => 'PDF redact',
						'desc_nl' => 'Zwart balken tekenen op PDF-pagina\'s; content wordt gerasteriseerd zodat tekst niet meer te extraheren is.',
						'desc_en' => 'Draw black bars on PDF pages; content is rasterised so text cannot be extracted.',
						'badge_nl' => 'Pro', 'badge_en' => 'Pro',
						'icon' => 'shield',
					],
					[
						'slug' => 'favicon-generator',
						'route' => 'tools.favicon-generator',
						'title_nl' => 'Favicon generator', 'title_en' => 'Favicon generator',
						'desc_nl' => 'Upload een logo, krijg alle standaard favicon-formaten + .ico in één ZIP.',
						'desc_en' => 'Upload a logo, get every standard favicon size + .ico in a single ZIP.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'image',
					],
				],
			],
			[
				'key' => 'security',
				'title_nl' => 'DNS, security & domeinen',
				'title_en' => 'DNS, security & domains',
				'subtitle_nl' => 'Live-lookups voor mail-, web- en certificaat-beveiliging.',
				'subtitle_en' => 'Live lookups for mail, web and certificate security.',
				'tools' => [
					[
						'slug' => 'dns-inspector',
						'route' => 'tools.dns-inspector',
						'title_nl' => 'DNS inspector', 'title_en' => 'DNS inspector',
						'desc_nl' => 'Bekijk A/AAAA/MX/NS/TXT/CNAME/SOA-records van een domein in één overzicht.',
						'desc_en' => 'View A/AAAA/MX/NS/TXT/CNAME/SOA records of a domain in one overview.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'globe',
					],
					[
						'slug' => 'mail-auth-check',
						'route' => 'tools.mail-auth',
						'title_nl' => 'SPF · DKIM · DMARC', 'title_en' => 'SPF · DKIM · DMARC',
						'desc_nl' => 'Test mail-authenticatie van een domein — direct rapport met verbeterpunten per record.',
						'desc_en' => 'Test mail authentication for a domain — instant report with improvements per record.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'mail',
					],
					[
						'slug' => 'ssl-check',
						'route' => 'tools.ssl-check',
						'title_nl' => 'SSL/TLS check', 'title_en' => 'SSL/TLS check',
						'desc_nl' => 'Live TLS-handshake: uitgever, vervaldatum, SANs, sleutel-info + waarschuwingen.',
						'desc_en' => 'Live TLS handshake: issuer, expiry, SANs, key info + warnings.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'shield',
					],
					[
						'slug' => 'security-headers',
						'route' => 'tools.headers-analyzer',
						'title_nl' => 'Security headers', 'title_en' => 'Security headers',
						'desc_nl' => 'HSTS, CSP, X-Frame-Options en meer. A-F grade plus uitleg per ontbrekende header.',
						'desc_en' => 'HSTS, CSP, X-Frame-Options and more. A-F grade plus per-missing-header explanation.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'lock',
					],
					[
						'slug' => 'whois-lookup',
						'route' => 'tools.whois-lookup',
						'title_nl' => 'WHOIS lookup', 'title_en' => 'WHOIS lookup',
						'desc_nl' => 'Registrar, registrant en vervaldatum van een domein. .nl, .com, .be, .de, .fr en meer.',
						'desc_en' => 'Registrar, registrant and expiry of a domain. .nl, .com, .be, .de, .fr and more.',
						'badge_nl' => 'Gratis', 'badge_en' => 'Free',
						'icon' => 'search',
					],
				],
			],
		];

		return view('pages.tools-index', ['sections' => $sections]);
	}
}
